name: Generate 3D Contribution Calendar

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: felipecezar01
          SETTING_JSON: |
            {
              "githubUserName": "felipecezar01",
              "startForegroundColor": "#a960ee",
              "endForegroundColor": "#ff333d",
              "bgColor": "#1a1b27",
              "dotColor": "#38bdae",
              "lineColor": "#bf91f3",
              "textColor": "#70a5fd",
              "drawShadow": true,
              "showBorder": false
            }
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
